
BNRP_initializeRing0"1343 N {nibi33;EPixBNRP_embedContext_base03<(53EP),59ioBNRP_bindRing05;(69EP);ilcheckInited73(7>);ioBNRP_bindRing083(91);AH(9:ibi9;=9=CM;ibi:2icLT:4ieargc:7;CE:=ibi:?)DB(;7igstrcmp;8(;>ieargv;?[<3ibi<4],<6s)icEQ=1CN)AL(>0inBNRP_loadBase>1(>>CM,?0ieargv?2,?6ieargv?8[?<ibi?=+?>CM]));AL(AAKinBNRP_loadBaseAAL(ABICM,ABKieargvABM,ACAs));ixBNRP_embedIgnoreContextADG=AEOCM;ixBNRP_embedContext_base0AFE(AGL);ixBNRP_embedIgnoreContextAHA=AIICN;AL(AJECN);}AKB
BNRP_initializeRing1"1804 N {nibi33;EPixBNRP_embedContext_base13<(53EP),59ioBNRP_bindRing15;(69EP);ilcheckInited73(7>);ioBNRP_bindRing183(91);AH(9:ibi9;=9=CM;ibi:2icLT:4ieargc:7;CE:=ibi:?)DB(;7igstrcmp;8(;>ieargv;?[<3ibi<4],<6s)icEQ=1CN)AL(>0inBNRP_loadBase>1(>>CM,?0ieargv?2,?6ieargv?8[?<ibi?=+?>CM]));AL(AAKinBNRP_loadBaseAAL(ABICM,ABKieargvABM,ACAs));ixBNRP_embedIgnoreContextADG=AEOCM;ixBNRP_embedContext_base1AFE(AGL);ixBNRP_embedIgnoreContextAHA=AIICN;AL(AJECN);}AKB
BNRP_initializeRing2"2265 N {nibi33;EPixBNRP_embedContext_base23<(53EP),59ioBNRP_bindRing25;(69EP);ilcheckInited73(7>);ioBNRP_bindRing283(91);AH(9:ibi9;=9=CM;ibi:2icLT:4ieargc:7;CE:=ibi:?)DB(;7igstrcmp;8(;>ieargv;?[<3ibi<4],<6s)icEQ=1CN)AL(>0inBNRP_loadBase>1(>>CM,?0ieargv?2,?6ieargv?8[?<ibi?=+?>CM]));AL(AAKinBNRP_loadBaseAAL(ABICM,ABKieargvABM,ACAs));ixBNRP_embedIgnoreContextADG=AEOCM;ixBNRP_embedContext_base2AFE(AGL);ixBNRP_embedIgnoreContextAHA=AIICN;AL(AJECN);}AKB
BNRP_initializeRing3"2726 N {nibi33;EPixBNRP_embedContext_base33<(53EP),59ioBNRP_bindRing35;(69EP);ilcheckInited73(7>);ioBNRP_bindRing383(91);AH(9:ibi9;=9=CM;ibi:2icLT:4ieargc:7;CE:=ibi:?)DB(;7igstrcmp;8(;>ieargv;?[<3ibi<4],<6s)icEQ=1CN)AL(>0inBNRP_loadBase>1(>>CM,?0ieargv?2,?6ieargv?8[?<ibi?=+?>CM]));AL(AAKinBNRP_loadBaseAAL(ABICM,ABKieargvABM,ACAs));ixBNRP_embedIgnoreContextADG=AEOCM;ixBNRP_embedContext_base3AFE(AGL);ixBNRP_embedIgnoreContextAHA=AIICN;AL(AJECN);}AKB
BNRP_initializeRing4"3187 N {nibi33;EPixBNRP_embedContext_base43<(53EP),59ioBNRP_bindRing45;(69EP);ilcheckInited73(7>);ioBNRP_bindRing483(91);AH(9:ibi9;=9=CM;ibi:2icLT:4ieargc:7;CE:=ibi:?)DB(;7igstrcmp;8(;>ieargv;?[<3ibi<4],<6s)icEQ=1CN)AL(>0inBNRP_loadBase>1(>>CM,?0ieargv?2,?6ieargv?8[?<ibi?=+?>CM]));AL(AAKinBNRP_loadBaseAAL(ABICM,ABKieargvABM,ACAs));ixBNRP_embedIgnoreContextADG=AEOCM;ixBNRP_embedContext_base4AFE(AGL);ixBNRP_embedIgnoreContextAHA=AIICN;AL(AJECN);}AKB
myTestProc"3649 N {*29ibc2:=2<iba2>+30ibb32;}37
myTest2"3713 N {*31icld32=35ibf37+39ibd3;;}40
BNRP_initializeRing5"3804 N {nibi33;EPixBNRP_embedContext_base53<(53EP),59ioBNRP_bindRing55;(69EP);ilcheckInited73(7>);ioBNRP_bindRing583(91);(:2EP)isBNRP_bindProcedure:8(;:s,<1(<3ioBNRP_procedure<4)ikmyTestProc=3,==CM,>0ioBNRP_shortParm>2,?0imBNRP_intParm?2,?>iqBNRP_varLongParmA@@);(AADEP)isBNRP_bindProcedureAAJ(ABLs,ACD(ACFioBNRP_procedureACG)ihmyTest2ADF,ADMCM,AE@ioBNRP_floatParmAEB,AF@ipBNRP_doubleParmAFB,AGAiuBNRP_varExtendedParmAGC);ipBNRP_setupFilesAIB(AJAieargcAJB,AJFieargvAJH);AH(AKDibiAKE=AKGCM;ibiAKLicLTAKNieargcALA;CEALGibiALI)DB(AMAigstrcmpAMB(AMHieargvAMI[AMMibiAMN],AN@s)icEQANKCN)AL(AOJinBNRP_loadBaseAOK(B@HCM,B@JieargvB@L,BA@ieargvBAB[BAFibiBAG+BAHCM]));AL(BCEinBNRP_loadBaseBCF(BDCCM,BDEieargvBDG,BDKs));ixBNRP_embedIgnoreContextBFA=BGICM;ixBNRP_embedContext_base5BGO(BIF);ixBNRP_embedIgnoreContextBIK=BKCCN;AL(BKOCN);}BLL
BNRP_initializeAllLowerRings"4548 N {EPioBNRP_bindRing53<(4:EP);ioBNRP_bindRing554(62);(73EP)isBNRP_bindProcedure79(8;s,92(94ioBNRP_procedure95)ikmyTestProc:4,:>CM,;1ioBNRP_shortParm;3,<1imBNRP_intParm<3,<?iqBNRP_varLongParm=1);(>5EP)isBNRP_bindProcedure>;(?=s,A@E(A@GioBNRP_procedureA@H)ihmyTest2AAG,AANCM,ABAioBNRP_floatParmABC,ACAipBNRP_doubleParmACC,ADBiuBNRP_varExtendedParmADD);{DMibfAFD=AFFCO;DJibdAGF=AGHCO;EADJicldAHM;ihmyTest2AIC(AIJibfAIK,AILibdAIM,AIN&AIOicldAJ@);}AJGipBNRP_setupFilesAKA(AL@ieargcALA,ALEieargvALG);}ALO