/*
 *
 * $Header: /disc9/sniff/repository/BNRProlog/utilities/RCS/reserved.p,v 1.2 1996/02/01 03:36:34 yanzhou Exp $
 *
 * $Log: reserved.p,v $
 * Revision 1.2  1996/02/01  03:36:34  yanzhou
 * New reserved symbols:
 *   bitand, butnot, bitshift, bitor, biteq
 *   defaultbitmapdir
 *   acceptconnection, makeconnection,
 *   opensocket, listensocket, closesocket,
 *   sendUDP, sendTCP, receiveUDP, receiveTCP,
 *   networkconfig, querysockets,
 *   querysocketopts and setsocketopts.
 *
 * Revision 1.1  1995/09/22  11:27:38  harrisja
 * Initial version.
 *
*
*/

% reserved_symbol(Symbol,Subsystem,Document,Ring).
% where
% Symbol is the reserved symbol.
% Subsystem is the part of the system where the symbol is defined. Roughly
%                 corresponds to the chapter headings in the Reference Manual. 
% Document may be reference_manual, constraint_doc, environment_guide,
%                 graphics_tech_note, panels_doc or undocumented.
%                 reference_manual refers to the BNR Prolog Reference Manual, 
%                 BNR Prolog Version 3.1 Reference Manual supplement, and 
%                 BNR Prolog Version 4.2 Delta document which together 
%                 comprise the most uptodate BNR Prolog Reference Manual.
% Ring is either the base ring where the symbol is defined or the name of 
%                 context.

reserved_symbol('!',control,reference_manual,0).
reserved_symbol('*',arithmetic,reference_manual,0).
reserved_symbol('**',arithmetic,reference_manual,0).
reserved_symbol('+',arithmetic,reference_manual,0).
reserved_symbol('-',arithmetic,reference_manual,0).
reserved_symbol('->',control,reference_manual,0).
reserved_symbol('/',arithmetic,reference_manual,0).
reserved_symbol('//',arithmetic,reference_manual,0).
reserved_symbol(':',constraint,constraint_doc,5).
reserved_symbol(':-',control,reference_manual,0).
reserved_symbol(':=',constraint,constraint_doc,5).
reserved_symbol(';',control,reference_manual,0).
reserved_symbol('<',arithmetic,reference_manual,0).
reserved_symbol('<=',arithmetic,reference_manual,0).
reserved_symbol('<>',arithmetic,reference_manual,0).
reserved_symbol('=',control,reference_manual,0).
reserved_symbol('=:=',edinburgh,reference_manual,0).
reserved_symbol('=<',arithmetic,reference_manual,0).
reserved_symbol('==',arithmetic,reference_manual,0).
reserved_symbol('=\\=',arithmetic,reference_manual,0).
reserved_symbol('=|',constraint,constraint_doc,5).
reserved_symbol('>',arithmetic,reference_manual,0).
reserved_symbol('>=',arithmetic,reference_manual,0).
reserved_symbol('?-',listener,environment_guide,5).
reserved_symbol('@<',meta_predicates,reference_manual,1).
reserved_symbol('@=',meta_predicates,reference_manual,1).
reserved_symbol('@=<',meta_predicates,reference_manual,1).
reserved_symbol('@>',meta_predicates,reference_manual,1).
reserved_symbol('@>=',meta_predicates,reference_manual,1).
reserved_symbol('@\\=',meta_predicates,reference_manual,1).
reserved_symbol('\\=',control,reference_manual,0).
reserved_symbol('\\==',edinburgh,reference_manual,1).
reserved_symbol(acceptconnection,networking,reference_manual,5).
reserved_symbol(accumulate,constraint,constraint_doc,5).
reserved_symbol(activewindow,windows,reference_manual,6).
reserved_symbol(acyclic,filter,reference_manual,1).
reserved_symbol(additem,menus,reference_manual,6).
reserved_symbol(addmenu,menus,reference_manual,6).
reserved_symbol(addresitems,menus,reference_manual,6).
reserved_symbol(and,constraint,constraint_doc,5).
reserved_symbol(angle,graphics_descriptor,reference_manual,6).
reserved_symbol(applicationdir,file_system,reference_manual,4).
reserved_symbol(arcabs,graphics_descriptor,reference_manual,6).
reserved_symbol(arcabs_C,graphics_primitive,graphics_tech_note,6).
reserved_symbol(arcrel,graphics_descriptor,reference_manual,6).
reserved_symbol(arg,meta_predicates,reference_manual,1).
reserved_symbol(assert,knowledge_base,reference_manual,4).
reserved_symbol(asserta,knowledge_base,reference_manual,4).
reserved_symbol(assertz,knowledge_base,reference_manual,4).
reserved_symbol(at,text_io,reference_manual,4).
reserved_symbol(atomic,filter,reference_manual,0).
reserved_symbol(attention_handler,debugger,reference_manual,debugger).
reserved_symbol(attention_handler,debug_hooks,reference_manual,5).
reserved_symbol(backcolor,graphics_descriptor,reference_manual,6).
reserved_symbol(backcolor_C,graphics_primitive,graphics_tech_note,6).
reserved_symbol(backpat,graphics_descriptor,reference_manual,6).
reserved_symbol(backpat_C,graphics_primitive,graphics_tech_note,6).
reserved_symbol(beep,system_utilities,reference_manual,6).
reserved_symbol(beginpicture,pictures,reference_manual,6).
reserved_symbol(bind_vars,meta_predicates,reference_manual,1).
reserved_symbol(bitand,arithmetic,reference_manual,0).
reserved_symbol(bitor,arithmetic,reference_manual,0).
reserved_symbol(bitshift,arithmetic,reference_manual,0).
reserved_symbol(biteq,arithmetic,reference_manual,0).
reserved_symbol(block,control,reference_manual,0).
reserved_symbol(boolean,constraint,constraint_doc,5).
reserved_symbol(bounding_rect,graphics,reference_manual,6).
reserved_symbol(breadth_first_compare,meta_predicates,reference_manual,1).
reserved_symbol(break,debug_hooks,reference_manual,5).
reserved_symbol(butnot,arithmetic,reference_manual,0).
reserved_symbol(caller,debug_hooks,reference_manual,5).
reserved_symbol(capsule,system_predicates,reference_manual,0).
reserved_symbol(changedtext,windows,reference_manual,6).
reserved_symbol(char_int,symbol_manipulation,reference_manual,1).
reserved_symbol(circleabs,graphics_descriptor,reference_manual,6).
reserved_symbol(circlerel,graphics_descriptor,reference_manual,6).
reserved_symbol(clause,knowledge_base,reference_manual,4).
reserved_symbol(clause_head,knowledge_base,reference_manual,4).
reserved_symbol(clause$$,reserved_symbol,reference_manual,4).
reserved_symbol(clone_GC,graphics_primitive,graphics_tech_note,6).
reserved_symbol(clone_GC_C,graphics_primitive,graphics_tech_note,6).
reserved_symbol(close,text_io,reference_manual,4).
reserved_symbol(close_definition,knowledge_base,reference_manual,3).
reserved_symbol(closed_definition,knowledge_base,reference_manual,3).
reserved_symbol(closeresfile,file_system,reference_manual,6).
reserved_symbol(closesocket,networking,reference_manual,5).
reserved_symbol(closewindow,windows,reference_manual,6).
reserved_symbol(compile,compiler,reference_manual,compile).
reserved_symbol(compile_clause,knowledge_base,reference_manual,4).
reserved_symbol(compound,filter,reference_manual,0).
reserved_symbol(concat,symbol_manipulation,reference_manual,1).
reserved_symbol(configuration,system_predicates,reference_manual,5).
reserved_symbol(confirm,dialogs,reference_manual,6).
reserved_symbol(constraint_network,constraint,constraint_doc,5).
reserved_symbol(consult,knowledge_base,reference_manual,3).
reserved_symbol(contents,knowledge_base,reference_manual,3).
reserved_symbol(context,knowledge_base,reference_manual,3).
reserved_symbol(continue,debug_hooks,reference_manual,5).
reserved_symbol(copyfile,file_system,reference_manual,6).
reserved_symbol(count,control,reference_manual,1).
reserved_symbol(counter_value,assignable_vars,reference_manual,1).
reserved_symbol(createdirectory,file_system,reference_manual,4).
reserved_symbol(createfile,file_system,reference_manual,6).
reserved_symbol(crectabs,graphics_descriptor,reference_manual,6).
reserved_symbol(crectabs_C,graphics_primitive,graphics_tech_note,6).
reserved_symbol(crectrel,graphics_descriptor,reference_manual,6).
reserved_symbol(cut,control,reference_manual,0).
reserved_symbol(cwamversion,knowledge_base,reference_manual,4).
reserved_symbol(debug,debugger,reference_manual,debugger).
reserved_symbol(debugevents,debugger,reference_manual,debugger).
reserved_symbol(decompose,meta_predicates,reference_manual,1).
reserved_symbol(defaultbitmapdir,graphics_primitive,reference_manual,6).
reserved_symbol(defaultdir,file_system,reference_manual,4).
reserved_symbol(definition,knowledge_base,reference_manual,4).
reserved_symbol(degrees_of_freedom,constraint,constraint_doc,5).
reserved_symbol(delay,system_predicates,reference_manual,1).
reserved_symbol(deletedirectory,file_system,reference_manual,4).
reserved_symbol(deletefile,file_system,reference_manual,4).
reserved_symbol(deleteitem,menus,reference_manual,6).
reserved_symbol(deletemenu,menus,reference_manual,6).
reserved_symbol(deletepicture,pictures,reference_manual,6).
reserved_symbol(deleteresource,file_system,reference_manual,6).
reserved_symbol(dispatch_panel_event,panels,panels_doc,6).
reserved_symbol(dispose_obj,state_space,reference_manual,1).
reserved_symbol(do,control,reference_manual,0).
reserved_symbol(do,graphics_descriptor,reference_manual,6).
reserved_symbol(dograf,windows,reference_manual,6).
reserved_symbol(domain,constraint,constraint_doc,5).
reserved_symbol(dotext,windows,reference_manual,6).
reserved_symbol(doubletime,system_utilities,reference_manual,6).
reserved_symbol(dragregion,graphics,reference_manual,6).
reserved_symbol(editbabs,graphics,reference_manual,6).
reserved_symbol(editbabs_C,graphics_primitive,graphics_tech_note,6).
reserved_symbol(editbrel,graphics,reference_manual,6).
reserved_symbol(enable_timer,system_predicates,reference_manual,1).
reserved_symbol(enable_trace,debug_hooks,reference_manual,5).
reserved_symbol(endpicture,pictures,reference_manual,6).
reserved_symbol(enter_context,knowledge_base,reference_manual,3).
reserved_symbol(enumerate,constraint,constraint_doc,5).
reserved_symbol(error,system_predicates,reference_manual,0).
reserved_symbol(error_string,system_predicates,reference_manual,5).
reserved_symbol(eval,temporary,undocumented,0).
reserved_symbol(exit_context,knowledge_base,reference_manual,3).
reserved_symbol(fail,control,reference_manual,0).
reserved_symbol(failexit,control,reference_manual,0).
reserved_symbol(fillpat,graphics_descriptor,reference_manual,6).
reserved_symbol(fillpat_C,graphics_primitive,graphics_tech_note,6).
reserved_symbol(findall,control,reference_manual,1).
reserved_symbol(findfileposition,text_io,reference_manual,6).
reserved_symbol(findinfo,windows,reference_manual,6).
reserved_symbol(findset,control,reference_manual,1).
reserved_symbol(firstfail,constraint,constraint_doc,5).
reserved_symbol(float,filter,reference_manual,0).
reserved_symbol(foreach,control,reference_manual,0).
reserved_symbol(forecolor,graphics_descriptor,reference_manual,6).
reserved_symbol(forecolor_C,graphics_primitive,graphics_tech_note,6).
reserved_symbol(forget,state_space,reference_manual,1).
reserved_symbol(forget_all,state_space,reference_manual,1).
reserved_symbol(free_GC,graphics_primitive,graphics_tech_note,6).
reserved_symbol(free_GC_C,graphics_primitive,graphics_tech_note,6).
reserved_symbol(freeze,control,reference_manual,1).
reserved_symbol(fullfilename,file_system,reference_manual,4).
reserved_symbol(gc,system_predicates,reference_manual,0).
reserved_symbol(gensym,symbol_manipulation,reference_manual,1).
reserved_symbol(get_char,text_io,reference_manual,4).
reserved_symbol(get_error_code,system_predicates,reference_manual,0).
reserved_symbol(get_obj,state_space,reference_manual,1).
reserved_symbol(get_term,text_io,reference_manual,[2,4]).
reserved_symbol(getappfiles,system_utilities,reference_manual,4).
reserved_symbol(getenv,system_predicates,reference_manual,5).
reserved_symbol(global_value,assignable_vars,reference_manual,1).
reserved_symbol(goal,debug_hooks,reference_manual,5).
reserved_symbol(graf_attr_desc,graphics_primitive,graphics_tech_note,6).
reserved_symbol(graf_output_desc,graphics_primitive,graphics_tech_note,6).
reserved_symbol(grand_caller,debug_hooks,reference_manual,5).
reserved_symbol(ground,filter,reference_manual,1).
reserved_symbol(halt,system_predicates,reference_manual,0).
reserved_symbol(hide,knowledge_base,reference_manual,3).
reserved_symbol(hidewindow,windows,reference_manual,6).
reserved_symbol('history',listener,environment_guide,5).
reserved_symbol(homedir,file_system,reference_manual,4).
reserved_symbol(iconabs,graphics_descriptor,reference_manual,6).
reserved_symbol(iconabs_C,graphics_primitive,graphics_tech_note,6).
reserved_symbol(iconrel,graphics_descriptor,reference_manual,6).
reserved_symbol(inq,graphics_descriptor,reference_manual,6).
reserved_symbol(inqangle,graphics_primitive,graphics_tech_note,6).
reserved_symbol(inqbackcolor,graphics_primitive,graphics_tech_note,6).
reserved_symbol(inqbackcolor_C,graphics_primitive,graphics_tech_note,6).
reserved_symbol(inqbackpat,graphics_primitive,graphics_tech_note,6).
reserved_symbol(inqbackpat_C,graphics_primitive,graphics_tech_note,6).
reserved_symbol(inqdo,graphics_primitive,graphics_tech_note,6).
reserved_symbol(inqfillpat,graphics_primitive,graphics_tech_note,6).
reserved_symbol(inqfillpat_C,graphics_primitive,graphics_tech_note,6).
reserved_symbol(inqforecolor,graphics_primitive,graphics_tech_note,6).
reserved_symbol(inqforecolor_C,graphics_primitive,graphics_tech_note,6).
reserved_symbol(inqgraf,windows,reference_manual,6).
reserved_symbol(inqinq,graphics_primitive,graphics_tech_note,6). 
reserved_symbol(inqoffset,graphics_primitive,graphics_tech_note,6).
reserved_symbol(inqpenmode,graphics_primitive,graphics_tech_note,6).
reserved_symbol(inqpenmode_C,graphics_primitive,graphics_tech_note,6).
reserved_symbol(inqpenpat,graphics_primitive,graphics_tech_note,6). 
reserved_symbol(inqpenpat_C,graphics_primitive,graphics_tech_note,6).
reserved_symbol(inqpensize,graphics_primitive,graphics_tech_note,6). 
reserved_symbol(inqpensize_C,graphics_primitive,graphics_tech_note,6).
reserved_symbol(inqposition,graphics_primitive,graphics_tech_note,6).
reserved_symbol(inqscale,graphics_primitive,graphics_tech_note,6). 
reserved_symbol(inqtext,windows,reference_manual,6).
reserved_symbol(inqtextface,graphics_primitive,graphics_tech_note,6).
reserved_symbol(inqtextface_C,graphics_primitive,graphics_tech_note,6).
reserved_symbol(inqtextfont,graphics_primitive,graphics_tech_note,6). 
reserved_symbol(inqtextfont_C,graphics_primitive,graphics_tech_note,6).
reserved_symbol(inqtextlines,graphics_primitive,graphics_tech_note,6). 
reserved_symbol(inqtextmode,graphics_primitive,graphics_tech_note,6). 
reserved_symbol(inqtextmode_C,graphics_primitive,graphics_tech_note,6).
reserved_symbol(inqtextsize,graphics_primitive,graphics_tech_note,6). 
reserved_symbol(inqtextsize_C,graphics_primitive,graphics_tech_note,6).
reserved_symbol(inqtextwidth,graphics_primitive,graphics_tech_note,6). 
reserved_symbol(inquserpat,graphics_primitive,graphics_tech_note,6). 
reserved_symbol(inquserpat_C,graphics_primitive,graphics_tech_note,6).
reserved_symbol(installmenu,menus,reference_manual,6).
reserved_symbol(integer,filter,reference_manual,[0,5]).
reserved_symbol(integer_range,arithmetic,reference_manual,1).
reserved_symbol(interval,filter,reference_manual,5).
reserved_symbol(invalidrect,system_utilities,reference_manual,6).
reserved_symbol(inventory,state_space,reference_manual,1).
reserved_symbol(is,arithmetic,reference_manual,0).
reserved_symbol(isdirectory,file_system,reference_manual,4).
reserved_symbol(isfile,file_system,reference_manual,4).
reserved_symbol(isfont,system_utilities,reference_manual,6).
reserved_symbol(ispanel,panels,panels_doc,6).
reserved_symbol(ispicture,pictures,reference_manual,6).
reserved_symbol(isvolume,file_system,reference_manual,4).
reserved_symbol(iswindow,windows,reference_manual,6).
reserved_symbol(lasteventdata,user_events,reference_manual,6).
reserved_symbol(lastmenudata,system_utilities,reference_manual,6).
reserved_symbol(lastparsererrorposition,text_io,reference_manual,4).
reserved_symbol(leash,debugger,reference_manual,debugger).
reserved_symbol(line,graphics_descriptor,reference_manual,6).
reserved_symbol(lineabs,graphics_descriptor,reference_manual,6).
reserved_symbol(lineabs_C,graphics_primitive,graphics_tech_note,6).
reserved_symbol(linerel,graphics_descriptor,reference_manual,6).
reserved_symbol(list,filter,reference_manual,0).
reserved_symbol(listdirectories,file_system,reference_manual,4).
reserved_symbol(listen,debug_hooks,reference_manual,5).
reserved_symbol(listener,debug_hooks,reference_manual,5).
reserved_symbol(listensocket,networking,reference_manual,5).
reserved_symbol(listfiles,file_system,reference_manual,4).
reserved_symbol(listfonts,system_utilities,reference_manual,6).
reserved_symbol(listing,knowledge_base,reference_manual,5).
reserved_symbol(listpictures,pictures,reference_manual,6).
reserved_symbol(listsizes,system_utilities,reference_manual,6).
reserved_symbol(listvolumes,file_system,reference_manual,4).
reserved_symbol(listwindows,windows,reference_manual,6).
reserved_symbol(load_context,knowledge_base,reference_manual,3).
reserved_symbol(loadpicture,pictures,reference_manual,6).
reserved_symbol(localglobal,system_utilities,reference_manual,6).
reserved_symbol(lower_bound,constraint,constraint_doc,5).
reserved_symbol(lowercase,symbol_manipulation,reference_manual,1).
reserved_symbol(makeconnection,networking,reference_manual,5).
reserved_symbol(mbarheight,system_utilities,reference_manual,6).
reserved_symbol(memory_status,system_predicates,reference_manual,1).
reserved_symbol(menuitem,menus,reference_manual,6).
reserved_symbol(menuselect,user_events,reference_manual,6).
reserved_symbol(message,dialogs,reference_manual,6).
reserved_symbol(mod,arithmetic,reference_manual,0).
reserved_symbol(move,graphics_descriptor,reference_manual,6).
reserved_symbol(moveabs,graphics_descriptor,reference_manual,6).
reserved_symbol(moverel,graphics_descriptor,reference_manual,6).
reserved_symbol(multi_lineabs_C,graphics_primitive,graphics_tech_note,6).
reserved_symbol(name,symbol_manipulation,reference_manual,1).
reserved_symbol(nameafile,dialogs,reference_manual,6).
reserved_symbol(namelength,symbol_manipulation,reference_manual,1).
reserved_symbol(nand,constraint,constraint_doc,5).
reserved_symbol(netname,networking,reference_manual,5).
reserved_symbol(networkconfig,networking,reference_manual,5).
reserved_symbol(new_counter,assignable_vars,reference_manual,1).
reserved_symbol(new_global,assignable_vars,reference_manual,1).
reserved_symbol(new_obj,state_space,reference_manual,1).
reserved_symbol(new_state,state_space,reference_manual,1).
reserved_symbol(nextevent,user_events,reference_manual,6).
reserved_symbol(nl,text_io,reference_manual,4).
reserved_symbol(nodebug,debugger,reference_manual,debugger).
reserved_symbol(nonfloat,filter,reference_manual,0).
reserved_symbol(noninteger,filter,reference_manual,0).
reserved_symbol(nonlist,filter,reference_manual,0).
reserved_symbol(nonnumber,filter,reference_manual,0).
reserved_symbol(nonnumeric,filter,reference_manual,0).
reserved_symbol(nonstructure,filter,reference_manual,0).
reserved_symbol(nonsymbol,filter,reference_manual,0).
reserved_symbol(nonvar,filter,reference_manual,0).
reserved_symbol(nor,constraint,constraint_doc,5).
reserved_symbol(nospy,debugger,reference_manual,debugger).
reserved_symbol(nospyall,debugger,reference_manual,debugger).
reserved_symbol(not,control,reference_manual,0).
reserved_symbol(notrace,debugger,reference_manual,debugger).
reserved_symbol(nth_solution,control,reference_manual,1).
reserved_symbol(number,filter,reference_manual,0).
reserved_symbol(numeric,filter,reference_manual,0).
reserved_symbol(occurs_in,meta_predicates,reference_manual,1).
reserved_symbol(offset,graphics_descriptor,reference_manual,6).
reserved_symbol(once,control,reference_manual,0).
reserved_symbol(op,operators,reference_manual,0).
reserved_symbol(open,text_io,reference_manual,4).
reserved_symbol(openresfile,file_system,reference_manual,6).
reserved_symbol(opensocket,networking,reference_manual,5).
reserved_symbol(openwindow,windows,reference_manual,6).
reserved_symbol(or,constraint,constraint_doc,5).
reserved_symbol(ovalabs,graphics_descriptor,reference_manual,6).
reserved_symbol(ovalabs_C,graphics_primitive,graphics_tech_note,6).
reserved_symbol(ovalrel,graphics_descriptor,reference_manual,6).
reserved_symbol(panel_attribute,panels,panels_doc,6).
reserved_symbol(panel_close,panels,panels_doc,6).
reserved_symbol(panel_create,panels,panels_doc,6).
reserved_symbol(panel_definition,panels,panels_doc,6).
reserved_symbol(panel_event,panels,panels_doc,6).
reserved_symbol(panel_expand_rect,panels,panels_doc,6).
reserved_symbol(panel_id,panels,panels_doc,6).
reserved_symbol(panel_item_class,panels,panels_doc,6).
reserved_symbol(panel_item_graf,panels,panels_doc,6).
reserved_symbol(panel_item_grow,panels,panels_doc,6).
reserved_symbol(panel_item_hit,panels,panels_doc,6).
reserved_symbol(panel_item_new,panels,panels_doc,6).
reserved_symbol(panel_item_read,panels,panels_doc,6).
reserved_symbol(panel_item_write,panels,panels_doc,6).
reserved_symbol(panel_list_line_graf,panels,panels_doc,6).
reserved_symbol(panel_menu,panels,panels_doc,6).
reserved_symbol(panel_open,panels,panels_doc,6).
reserved_symbol(panel_rename,panels,panels_doc,6).
reserved_symbol(panel_reopen,panels,panels_doc,6).
reserved_symbol(panel_save,panels,panels_doc,6).
reserved_symbol(panel_scroll_item,panels,panels_doc,6).
reserved_symbol(panel_scroll_item_adjust,panels,panels_doc,6).
reserved_symbol(panel_scroll_item_info,panels,panels_doc,6).
reserved_symbol(panel_scroll_vslider,panels,panels_doc,6).
reserved_symbol(panel_target_item,panels,panels_doc,6).
reserved_symbol(panel_text_size,panels,panels_doc,6).
reserved_symbol(panel_view,panels,panels_doc,6).
reserved_symbol(panelfont,panels,panels_doc,6).
reserved_symbol(pde_init,system_predicates,reference_manual,5).
reserved_symbol(penmode,graphics_descriptor,reference_manual,6).
reserved_symbol(penmode_C,graphics_primitive,graphics_tech_note,6).
reserved_symbol(penpat,graphics_descriptor,reference_manual,6).
reserved_symbol(penpat_C,graphics_primitive,graphics_tech_note,6).
reserved_symbol(pensize,graphics_descriptor,reference_manual,6).
reserved_symbol(pensize_C,graphics_primitive,graphics_tech_note,6).
reserved_symbol(pictabs,graphics_descriptor,reference_manual,6).
reserved_symbol(pictrel,graphics_descriptor,reference_manual,6).
reserved_symbol(picttoscrap,pictures,reference_manual,6).
reserved_symbol(polygon,graphics_descriptor,reference_manual,6).
reserved_symbol(polygon_C,graphics_primitive,graphics_tech_note,6).
reserved_symbol(popupmenu,menus,reference_manual,6).
reserved_symbol(portray,text_io,reference_manual,5).
reserved_symbol(portray_with_indent,text_io,reference_manual,5).
reserved_symbol(position,graphics_descriptor,reference_manual,6).
reserved_symbol(positionwindow,windows,reference_manual,6).
reserved_symbol(postevent,user_events,reference_manual,6).
reserved_symbol(predicate,knowledge_base,reference_manual,3).
reserved_symbol(presolve,constraint,constraint_doc,5).
reserved_symbol(primitive,knowledge_base,reference_manual,3).
reserved_symbol(print,text_io,reference_manual,5).
reserved_symbol(printfile,file_system,reference_manual,6).
reserved_symbol(printpicture,pictures,reference_manual,6).
reserved_symbol(prologwindows,windows,reference_manual,6).
reserved_symbol(put_char,text_io,reference_manual,4).
reserved_symbol(put_obj,state_space,reference_manual,1).
reserved_symbol(put_term,text_io,reference_manual,[2,4]).
reserved_symbol(query,dialogs,reference_manual,6).
reserved_symbol(queryfind,dialogs,reference_manual,6).
reserved_symbol(queryformat,dialogs,reference_manual,6).
reserved_symbol(queryreplace,dialogs,reference_manual,6).
reserved_symbol(querysocketopts,networking,reference_manual,5).
reserved_symbol(querysockets,networking,reference_manual,5).
reserved_symbol(quit,system_predicates,reference_manual,0).
reserved_symbol(read,text_io,reference_manual,4).
reserved_symbol(readfile,text_io,reference_manual,4).
reserved_symbol(readln,text_io,reference_manual,4).
reserved_symbol(readresource,file_system,reference_manual,6).
reserved_symbol(recall,state_space,reference_manual,1).
reserved_symbol(receiveTCP,networking,reference_manual,5).
reserved_symbol(receiveUDP,networking,reference_manual,5).
reserved_symbol(reconsult,knowledge_base,reference_manual,4).
reserved_symbol(recovery_unit,system_predicates,userguide,0).
reserved_symbol(rectabs,graphics_descriptor,reference_manual,6).
reserved_symbol(rectabs_C,graphics_primitive,graphics_tech_note,6).
reserved_symbol(rectrel,graphics_descriptor,reference_manual,6).
reserved_symbol(reeventdata,user_events,reference_manual,6).
reserved_symbol(reload_context,knowledge_base,reference_manual,4).
reserved_symbol(reloadtext,windows,reference_manual,6).
reserved_symbol(remember,state_space,reference_manual,1).
reserved_symbol(remembera,state_space,reference_manual,1).
reserved_symbol(rememberz,state_space,reference_manual,1).
reserved_symbol(renamefile,file_system,reference_manual,6).
reserved_symbol(renamewindow,windows,reference_manual,6).
reserved_symbol(repeat,control,reference_manual,0).
reserved_symbol(retargettext,windows,reference_manual,6).
reserved_symbol(retract,knowledge_base,reference_manual,4).
reserved_symbol(retractall,knowledge_base,reference_manual,4).
reserved_symbol(rrectabs,graphics_descriptor,reference_manual,6).
reserved_symbol(rrectabs_C,graphics_primitive,graphics_tech_note,6).
reserved_symbol(rrectrel,graphics_descriptor,reference_manual,6).
reserved_symbol(savepicture,pictures,reference_manual,6).
reserved_symbol(savetext,windows,reference_manual,6).
reserved_symbol(scale,graphics_descriptor,reference_manual,6).
reserved_symbol(scrapcontents,system_utilities,reference_manual,6).
reserved_symbol(scraptopict,pictures,reference_manual,6).
reserved_symbol(scraptotext,system_utilities,reference_manual,6).
reserved_symbol(scrndimensions,system_utilities,reference_manual,6).
reserved_symbol(scrollrect,graphics_descriptor,reference_manual,6).
reserved_symbol(scrollrect_C,graphics_primitive,graphics_tech_note,6).
reserved_symbol(seek,text_io,reference_manual,4).
reserved_symbol(select,dialogs,reference_manual,6).
reserved_symbol(selectafile,dialogs,reference_manual,6).
reserved_symbol(selectone,dialogs,reference_manual,6).
reserved_symbol(sendTCP,networking,reference_manual,5).
reserved_symbol(sendUDP,networking,reference_manual,5).
reserved_symbol(set_end_of_file,text_io,reference_manual,4).
reserved_symbol(set_global,assignable_vars,reference_manual,1).
reserved_symbol(set_lower_bound,constraint,constraint_doc,5).
reserved_symbol(set_trace,debug_hooks,reference_manual,5).
reserved_symbol(set_trace_all,debug_hooks,reference_manual,5).
reserved_symbol(set_upper_bound,constraint,constraint_doc,5).
reserved_symbol(setcursor,system_utilities,reference_manual,6).
reserved_symbol(setsocketopts,networking,reference_manual,5).
reserved_symbol(sizewindow,windows,reference_manual,6).
reserved_symbol(solve,constraint,constraint_doc,5).
reserved_symbol(sort,meta_predicates,reference_manual,1).
reserved_symbol(spanning_tree,meta_predicates,reference_manual,1).
reserved_symbol(spied,debugger,reference_manual,debugger).
reserved_symbol(spy,debugger,reference_manual,debugger).
reserved_symbol(spyall,debugger,reference_manual,debugger).
reserved_symbol(sread,text_io,reference_manual,[2,4]).
reserved_symbol(stackwindows,windows,reference_manual,6).
reserved_symbol(state_changed,state_space,reference_manual,1).
reserved_symbol(stats,system_predicates,reference_manual,1).
reserved_symbol(stream,text_io,reference_manual,4).
reserved_symbol(stringlistresource,system_utilities,reference_manual,6).
reserved_symbol(stringresource,system_utilities,reference_manual,6).
reserved_symbol(structure,filter,reference_manual,0).
reserved_symbol(substring,symbol_manipulation,reference_manual,1).
reserved_symbol(subsumes,meta_predicates,reference_manual,1).
reserved_symbol(successor,arithmetic,reference_manual,1).
reserved_symbol(swrite,text_io,reference_manual,[2,4]).
reserved_symbol(swriteq,text_io,reference_manual,[2,4]).
reserved_symbol(symbol,filter,reference_manual,0).
reserved_symbol(symbol_name,knowledge_base,reference_manual,3).
reserved_symbol(system,system_utilities,reference_manual,5).
reserved_symbol(tailvar,filter,reference_manual,0).
reserved_symbol(term_compare,meta_predicates,reference_manual,1).
reserved_symbol(termlength,meta_predicates,reference_manual,1).
reserved_symbol(textabs,graphics_descriptor,reference_manual,6).
reserved_symbol(textabs_C,graphics_primitive,graphics_tech_note,6).
reserved_symbol(textbabs,graphics_descriptor,reference_manual,6).
reserved_symbol(textbrel,graphics_descriptor,reference_manual,6).
reserved_symbol(textface,graphics_descriptor,reference_manual,6).
reserved_symbol(textface_C,graphics_primitive,graphics_tech_note,6).
reserved_symbol(textfont,graphics_descriptor,reference_manual,6).
reserved_symbol(textfont_C,graphics_primitive,graphics_tech_note,6).
reserved_symbol(textlines,graphics_descriptor,reference_manual,6).
reserved_symbol(textlines_C,graphics_primitive,graphics_tech_note,6).
reserved_symbol(textmode,graphics_descriptor,reference_manual,6).
reserved_symbol(textmode_C,graphics_primitive,graphics_tech_note,6).
reserved_symbol(textrel,graphics_descriptor,reference_manual,6).
reserved_symbol(textsize,graphics_descriptor,reference_manual,6).
reserved_symbol(textsize_C,graphics_primitive,graphics_tech_note,6).
reserved_symbol(texttoscrap,system_utilities,reference_manual,6).
reserved_symbol(textwidth,graphics_descriptor,reference_manual,6).
reserved_symbol(textwidth_C,graphics_primitive,graphics_tech_note,6).
reserved_symbol(tilewindows,windows,reference_manual,6).
reserved_symbol(timedate,system_predicates,reference_manual,5).
reserved_symbol(tr,temporary,undocumented,R).
reserved_symbol(trace,debugger,reference_manual,debugger).
reserved_symbol(traceback,debug_hooks,reference_manual,5).
reserved_symbol(tracer,debugger,reference_manual,debugger).
reserved_symbol(true,control,reference_manual,0).
reserved_symbol(turn,graphics_descriptor,reference_manual,6).
reserved_symbol(unknown,debug_hooks,reference_manual,5).
reserved_symbol(update,state_space,reference_manual,1).
reserved_symbol(upper_bound,constraint,constraint_doc,5).
reserved_symbol(uppercase,symbol_manipulation,reference_manual,1).
reserved_symbol(useractivate,user_events,reference_manual,6).
reserved_symbol(userclose,user_events,reference_manual,6).
reserved_symbol(userdeactivate,user_events,reference_manual,6).
reserved_symbol(userdownidle,user_events,reference_manual,6).
reserved_symbol(userdrag,user_events,reference_manual,6).
reserved_symbol(userevent,user_events,reference_manual,6).
reserved_symbol(usergrow,user_events,reference_manual,6).
reserved_symbol(userkey,user_events,reference_manual,6).
reserved_symbol(usermousedown,user_events,reference_manual,6).
reserved_symbol(usermouseup,user_events,reference_manual,6).
reserved_symbol(userpat,graphics_descriptor,reference_manual,6).
reserved_symbol(userpat_C,graphics_primitive,graphics_tech_note,6).
reserved_symbol(userrename,user_events,reference_manual,6).
reserved_symbol(userreposition,user_events,reference_manual,6).
reserved_symbol(userresize,user_events,reference_manual,6).
reserved_symbol(userswitch,user_events,reference_manual,6).
reserved_symbol(userupdate,user_events,reference_manual,6).
reserved_symbol(userupidle,user_events,reference_manual,6).
reserved_symbol(validrect,system_utilities,reference_manual,6).
reserved_symbol(var,filter,reference_manual,0).
reserved_symbol(variables,meta_predicates,reference_manual,1).
reserved_symbol(version,system_predicates,reference_manual,0).
reserved_symbol(visible,knowledge_base,reference_manual,3).
reserved_symbol(voiditem,panels,panels,panels_doc,6).
reserved_symbol(where,control,reference_manual,0).
reserved_symbol(window_id,windows,graphics_tech_note,6).
reserved_symbol(with_context,knowledge_base,reference_manual,3).
reserved_symbol(write,text_io,reference_manual,4).
reserved_symbol(writeq,text_io,reference_manual,4).
reserved_symbol(writeresource,file_system,reference_manual,6).
reserved_symbol(xor,constraint,constraint_doc,5).
reserved_symbol('{}',control,reference_manual,1).
reserved_symbol('|=',constraint,constraint_doc,5).
reserved_symbol('~',constraint,constraint_doc,5).



