/*
*
*  $Header: /disc9/sniff/repository/BNRProlog/utilities/Panels_3.1/panel_files/RCS/Example_2.p,v 1.1 1995/09/22 11:24:06 harrisja Exp $
*
*  $Log: Example_2.p,v $
 * Revision 1.1  1995/09/22  11:24:06  harrisja
 * Initial version.
 *
*
*/

/*
 *   Example 2
 *
 *   BNR Prolog
 *
 *   Copyright © Bell-Northern Research Ltd. 1991
 */

/****************************************************************************/


% -- Event handlers --------------------------------------------

% This handler gives a popup menu of choices for the user to 
% select for entry into the field 'type'.  This is a often
% very desirable in data base access or forms filling applications.
% Notice that with panels the choice list need not be just a
% static domain value list, it can be the list of current
% possible choices for the field, taking into account all the
% other information in the panel.

panel_event('Example 2',select,field(type)):-
    findset(Type,food(Type,_),List),
    panel_menu('Example 2',List,Choice), % a handy menu utility
    findset(Food,food(Choice,Food),Feast),    
    panel_view('Example 2',type:=Choice,list:=contents(Feast..)).

% Transfer the 'doubleclicked' item of a list into a field.
% This shows how to deal with list objects: 

panel_event('Example 2',doubleclick,list(name(list),Etc..)):-
    panel_item_read(list(name(list),Etc..),selection(_,Eg)), % get selection from list
    panel_view('Example 2',eg:=Eg).

% Icons are just like buttons:

panel_event('Example 2',click,button(finger)):-
    panel_view('Example 2',eg:=beer),
    back_fill(beer).

% check_boxes have a value of on or off:

panel_event('Example 2',update,button('diet food')):-
    panel_view('Example 2','diet food':Diet),
    Diet = on -> Eg = water; Eg = pork,
    back_fill(Eg),
    panel_view('Example 2',eg:=Eg).

% close panel handler, gets rid of context and source window

panel_event('Example 2',close):-
    context('Example_2',Path),
    concat(Window,'.a',Path)->true;Window=Path,
    closewindow(Window)->true,
    exit_context('Example_2').

% -- support routines to access the example 'data base' --

back_fill(Example):-
    food(Type,Example),
    findset(Food,food(Type,Food),Feast),
    panel_view('Example 2',type:=Type,list:=contents(Feast..)).

% -- the example 'data base' --
    
food(drink,beer).
food(meat,beef).
food(meat,pork).
food(meat,lamb).
food(drink,wine).
food(fish,cod).
food(fish,tuna).
food(drink,water).
food(meat,chicken).
food(meat,turkey).
food(meat,duck).
food(meat,elk).
food(fish,salmon).
food(fish,trout).
food(fish,snapper).
food(drink,coffee).
food(drink,tea).


% -- panel layout generated by panel maker --


panel_definition('Example 2',
    pos(259,80),
    size(240,241),
    options(style(document),background(white,white),picture(),lock(off),dialog(off)),
    button('diet food',[68,208,146,225],['check box','diet food',off,font(0,12),icon(0),menu()]),
    button('Type:',[12,24,50,40],[transparent,'Type:',nil,font(0,12),icon(0),menu()]),
    button('Example:',[68,152,131,168],[transparent,'Example:',nil,font(0,12),icon(0),menu()]),
    button(finger,[16,168,48,200],[transparent,'',off,font(0,12),icon(32650),menu()]),
    field(eg,[68,174,168,194],[['','','',0],font(0,12),lock(off),lines(off),style(rectangle),menu()]),
    field(type,[68,22,168,42],[['','','',0],font(0,12),lock(off),lines(off),style(rectangle),menu()]),
    list(list,[68,62,188,144],_1)).

$initialization:-panel_open('Example 2').

