#
#  $Header: /disc9/sniff/repository/BNRProlog/prologSupport/RCS/makefile,v 1.1 1997/04/01 16:58:59 harrisj Exp $
#
#  $Log: makefile,v $
# Revision 1.1  1997/04/01  16:58:59  harrisj
# Added makefile to allow for updating prologSupport workspace
#
#
#

SNIFF_MAKEDIR=.sniffdir

include $(SNIFF_MAKEDIR)/macros.incl
include $(SNIFF_MAKEDIR)/vpath.incl
include $(WORKSPACE)/BNRProlog/prologSupport/BNRP.mk
include $(GMS_DIR)/common.mk 
