cp dotext.p xbase
cat acton.p >>xbase
cat dograf.p >>xbase
cat postscript.p >>xbase
cat textbox.p >>xbase
cat bounding_rect.p >>xbase
cat pictures.p >>xbase
cat dragregion.p >>xbase
cat PostEvent.p >>xbase
cat filemenu.p >>xbase
cat findmenu.p >>xbase
cat ContextsMenu.p >>xbase
cat stringlistresource.p >>xbase
cat windows.p >>xbase
cat windowpredicates.p >>xbase
cat resources.p >>xbase
cat menus.p >>xbase
cat panel_view.p >>xbase
cat panel_sys.p >>xbase
cat dialogs.p >>xbase
cat button_class.p >>xbase
cat field_class.p >>xbase
cat list_class.p >>xbase
cat panel_works.p >>xbase
cat defaultevents.p >>xbase
cat windowmenu.p >>xbase
cat editmenu.p >>xbase
cat helpmenu.p >>xbase
cat pde_init.p >>xbase
