cp dotext.p base
chmod u+w base
cat acton.p >>base
cat dograf.p >>base
cat postscript.p >>base
cat textbox.p >>base
cat bounding_rect.p >>base
cat pictures.p >>base
cat dragregion.p >>base
cat PostEvent.p >>base
cat filemenu.p >>base
cat findmenu.p >>base
cat ContextsMenu.p >>base
cat stringlistresource.p >>base
cat windows.p >>base
cat windowpredicates.p >>base
cat resources.p >>base
cat menus.p >>base
cat panel_view.p >>base
cat panel_sys.p >>base
cat dialogs.p >>base
cat button_class.p >>base
cat field_class.p >>base
cat list_class.p >>base
cat panel_works.p >>base
cat defaultevents.p >>base
cat windowmenu.p >>base
cat editmenu.p >>base
cat helpmenu.p >>base
cat ../build_base/base5.prolog >>base
cat pde_init.p >>base
